spring:
#  cloud:
#    gateway:
#      routes:
#        - id: account-service
#          uri: http://localhost:8081/
#          predicates:
#            - Path=/account/**
  application:
    name: api-gateway
server:
  port: 8070

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
